
[tool.briefcase]
project_name = "BitcoinZ Wallet"
bundle = "com.btcz"
version = "1.6.1"
url = "https://getbtcz.com"
license.file = "LICENSE"
author = "BTCZCommunity"
author_email = "None"

[tool.briefcase.app.BTCZWallet]
formal_name = "BTCZWallet"
description = """BitcoinZ Full Node Wallet GUI is user-friendly cryptocurrency wallet designed for storing and managing BitcoinZ (BTCZ) securely. This full node wallet allows users to interact directly with the BitcoinZ blockchain, giving them full control over their funds, while ensuring privacy and decentralization. With its Graphical User Interface (GUI), this wallet provides an intuitive experience for both new and experienced users. It enables you to securely send and receive BitcoinZ transactions, view your walletâ€™s transaction history, and monitor the current blockchain status, all through an easy-to-use interface.
"""
icon = "BTCZWallet/images/BitcoinZ"
sources = [
    "BTCZWallet",
]
test_sources = [
    "tests",
]

requires = [
]
test_requires = [
    "pytest",
]

[tool.briefcase.app.BTCZWallet.windows]
requires = ["-r", "requirements.txt"]

template = "./template"

